import {root} from "./main.js"

const exportButton = document.getElementById('export');

exportButton.onclick = () => {
    let exportedCode = [];
    // string interpolation is so cool
    exportedCode.push("/******************************");
    exportedCode.push(" * AUTOGENERATED MECHANISM 2D *");
    exportedCode.push(" ******************************/");
    exportedCode.push("");
    exportedCode.push("// Create Mechanism");
    exportedCode.push("Mechanism2d mech = new Mechanism2d(-1, -1); // README: change the dimensions to what works, usually doesnt have to be that high");
    exportedCode.push(`MechanismRoot2d ${root.name} = mech.getRoot(${root.x}, ${root.y}); // README: also change the position of the root to match the dimensions`);
    exportedCode.push("");
    exportedCode.push("// Objects");
    exportedCode.push("");

    // breadth-first traversal (so fancy)
    const queue = [];

    for (const [_, obj] of root.objects) {
        queue.push({
            object: obj,
            parent: root,
        });
    }

    while (queue.length > 0) {
        const { object, parent } = queue.shift();

        exportedCode.push(object.generateCode(parent));

        for (const [_, child] of object.objects) {
            queue.push({
                object: child,
                parent: object,
            });
        }
    }
    
    navigator.clipboard.writeText(exportedCode.join("\n")).then(() => alert("Code copied to clipboard!"));
};